

function response(theclaimed , relationship, length, personal){
     let obj = {
         'fwb' : [`Hey ,<a href="https://twitter.com/">@${theclaimed}</a., Anon says you guys have been duking it down for ${length} and ${personal} feelings their end. Do you want to find out who claimed you? Click the link in our bio to find out`, `@${theclaimed} what’s up between you and Anon that have been together for ${length}? Are you friends? Are you lovers? Is it just sex? What are you? Well, ${personal} feelings their end though. Find out who said you are FWBs with the link in our bio.`, `One of the many mysteries or life is how true love can come from anywhere? @${theclaimed} do not let this opportunity pass you by, Anon has claimed that you have been together for ${length} and ${personal} feelings their end. Could this be love? Is this claim right? Anon is waiting for you to confirm with the link in our bio.`, `Sometimes, your friend is actually your soulmate. @${theclaimed} Don’t you want to know who has claimed you for ${length} and ${personal} feelings their end? Click the link in our bio to find out.`, `Hello, relationship calling, why ah u running dear? @${theclaimed}. Anon thinks you are soulmates, afterall you have been slumming it for ${length} and ${personal} feelings their end. Click the link in our bio to discover who your new soulmate might be, you never know.`],
         'wife' : [`Hey @${theclaimed}, It is looking like this your marriage with Anon for ${length} that you both do the do on a ${personal} basis will last forever oh. Are you even married? Find out who claims to be married to you from the link in our bio.`, `Listen @${theclaimed}, true love is hard to find, hold your husband of ${length} tight to ya chest and keep slumming it on a ${personal} basis if not more o. Verify your wedding with the link in the bio`, `@${theclaimed} E be like say you don find your ride or die o, you guys be like bonnie and Clyde. Send your partner of about ${length} a sweet message too with the link in the bio and shag him more than ${personal} o.`, `This your marriage na die o haba, congratulations on winning the lottery for ${length}. The ${personal} sex can be improved too. @${theclaimed} but wait oh, are you really married to this person? Verify this claim with the link in the bio`, `@${theclaimed} Is your marriage heading for the rocks? The ${personal} sex for ${length} no dey enough o. Find out who thinks so with the link in the bio`],
         'boyfriend' : [`Hey @${theclaimed}, are you your bae’s bae? Has she wasted about ${length} thinking you are bae? She said ${personal}, when asked if you have cheated before.  Click the link in the bio to find out who thinks you are bae.`,`Hear ye hear ye @${theclaimed}, this thing with Anon must lead to marriage oh after ${length} together and ${personal}, unless... Click the link in the bio to verify this claim`, `Omo dem don make you fall in love oh, see as you dey shine like fluorescent bulb for ${length} and ${personal}. @${theclaimed} Verify this claim with the link in the bio.`, `Hold your significant other. Tell them that you love them. Put your lips together and plant a kiss. @${theclaimed} Find out who thinks you have been dating for about ${length} and said ${personal}, when asked if you have cheated before, with the link in the bio.`,`Is the bae you’re claiming, also claiming you? @${theclaimed} click to find out who this is your bae of ${length} is and ${personal} with the link in the bio!`],
         'girlfriend' : [`Hey @${theclaimed}, are you your bae’s bae? Has she wasted about ${length} thinking you are bae? She said ${personal}, when asked if you have cheated before.  Click the link in the bio to find out who thinks you are bae.`,`Hear ye hear ye @${theclaimed}, this thing with Anon must lead to marriage oh after ${length} together and ${personal}, unless... Click the link in the bio to verify this claim`, `Omo dem don make you fall in love oh, see as you dey shine like fluorescent bulb for ${length} and ${personal}. @${theclaimed} Verify this claim with the link in the bio.`, `Hold your significant other. Tell them that you love them. Put your lips together and plant a kiss. @${theclaimed} Find out who thinks you have been dating for about ${length} and said ${personal}, when asked if you have cheated before, with the link in the bio.`,`Is the bae you’re claiming, also claiming you? @${theclaimed} click to find out who this is your bae of ${length} is and ${personal} with the link in the bio!`]
     }
     let rand = getRandomInt(5);
     return obj[relationship][rand];


    }
    function getRandomInt(max) {
        return Math.floor(Math.random() * Math.floor(max));
    }
export default response;
